import 'package:get/get.dart';

class MyTranslation extends Translations{
  @override
  Map<String, Map<String, String>> get keys => {
    "ar" : {
      "1":"اختر اللغه",
      "2":"اختر المنتج",
      "3":"منجك من متجرنا نحن لدينا 100 الف منتج و اختر",
      "4":"سهل وأمن للشراء",
      "5":"يمكنك الدفع كاش او من خلال بوابات الدفع الالكتروني",
      "6":"تتبع طلبك",
      "7":"يمكنك تتبع طلبك في كل مرحله او من خلال الخريطة",
      "8":"متابعه",
      "9":"تسجيل الدخول",
      "10":"اهلا بك",
      "11":"يمكنك التسجيل عن طريق البريد او من حلال وسائل التواصل الاجتماعي",
      "12":"ادخل البريد الالكتروني",
      "13":"ادخل كلمه المرور",
      "14":"هل نسيت كلمه المرور",
      "15":"تسجيل الدخول",
      "16":"ليس لديك حساب؟",
      "17":"انشاء حساب",
      "18":"البريد الالكتروني",
      "19":"كلمة المرور",
      "20":"اسم المستخدم",
      "21":"رقم الهاتف",
      "22":"ادخل رقم الهاتف",
      "23":"ادخل اسم المستخدم",
      "24":"انشاء حساب عن طريق البريد \n او من خلال وسائل التواصل الاجتماعي",
      "25":"لديك حساب؟",
      "26":"تسجيل الدخول",
      "27":"فحص البريد الالكتروني",
      "28":"تم انشاء الحساب بنجاح",
      "29":"الرجاء ادخال البريد لتلقي رمز التحقق",
      "30":"فحص",
      "31":"الذهاب لتسجيل الدخول",
      "32":"نجاح",
      "33":"حفظ",
      "34":"الرجاء ادخال كلمه المرور الجديدة",
      "35":"الكبمة الجديدة",
      "36":"تم اعادة كلمة المرور بنجاح",
      "37":"تهانيئا",
      "38":"تم التسجيل بنجاح",
      "39":"إعادة تعيين كلمة المرور",
      "40":"أستمرار",
      "41":"تحذير",
      "42":"هل تريد الخروج من التطبيق",
      "43":"مواقق",
      "44":"الغاء!",

    },
    "en" : {
      "1":"Choose Language",
      "2":"Choose Product",
      "3":"Your product is from our store. We have 100,000 products and choose",
      "4":"It is easy and safe to purchase.",
      "5":"You can pay in cash or through electronic payment gateways.",
      "6":"Track your order",
      "7":"You can track your order at every stage or through the map.",
      "8":"Follow up,",
      "9":"Login",
      "10":"Welcome",
      "11":"You can register by mail or through social media",
      "12":"Enter your email",
      "13":"Enter the password",
      "14":"Forgot your password?",
      "15":"Login",
      "16":"You don't have an account?",
      "17":"Create an account",
      "18":"E-mail",
      "19":"password",
      "20":"Username",
      "21":"phone number",
      "22":"Enter the phone number",
      "23":"Enter the username",
      "24":"Create an account by mail or through social media",
      "25":"Do you have an account?",
      "26":"Login",
      "27":"E-Mail Check",
      "28":"The account has been created successfully",
      "29":"Please enter your email to receive the verification code",
      "30":"Check",
      "31":"Go to login",
      "32":"Success",
      "33":"Save",
      "34":"Please enter the new password",
      "35":"the new word",
      "36":"The password has been reset successfully",
      "37":"Congratulations",
      "38":"Registration completed successfully",
      "39":"Reset Password",
      "40":"Continue",
      "41":"Warning !",
      "42":"Do You Want to Exit the Application",
      "43":"Confirm",
      "44":"Cancel",
    },
  };

}